application: watercooler-966
version: dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"

handlers:
- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js
  
- url: /images
  static_dir: images


- url: /.*
  script: main.app
