application: watercooler-966
version: dev
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"

handlers:
- url: /.*
  script: main.app
